### ISSUE TITLE
MEM consistently increases error

### ISSUE THREAD

**Issue by RenatoFarruggio** [qiskit-community/may4_challenge_exercises#4]
Measurement error mitigation seems to increase error instead of decrease it. I've inverted all error mitigations in my head and I've got all answers right.
[Here's the first exercise](https://imgur.com/XeTu9KW) for example.

**Comment by dlyongemallo** [comment]
In your image, the blue bars are the mitigated counts and the red bars are the noisy counts, so the errors have been _decreased_. It looks right to me.

I think you may be confused because in the _previous_ image in the notebook, the blue bars were the noisy counts (but it's clear the noisy count colour has switched between plots if you look at the values).

**Comment by RenatoFarruggio** [comment]
You are right, I assumed the colors were fixed.
